[bar]
order = [ "TopBar" ]

    [bar.TopBar]
    background_opacity = 0.67999998480081558
    center = [ "battery", "clock", "tray", "media" ]
    end = [ "wallpaper", "network", "bluetooth", "brightness", "notifications", "session" ]
    margin_ends = 20
    margin_opposite_edge = 3
    start = [ "launcher", "control-center", "workspaces", "clipboard", "volume" ]
    widget_spacing = 15

[battery]
warning_threshold = 20

[dock]
background_opacity = 0.45999998971819878
concave_edge_corners = false
enabled = true
icon_size = 32
item_spacing = 8
magnification_scale = 1.2500000037252903
main_axis_padding = 8
pinned = [ "kitty", "code", "google-chrome" ]
radius_bottom_left = 0
radius_bottom_right = 0
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 62.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 60.0

[location]
address = "Shanghai, China"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 732.0
    cy = 732.0
    output = "eDP-1"
    placement_height = 914.0
    placement_width = 1463.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[shell]
avatar_path = "/home/licryle/Pictures/profile.jpg"
screen_time_enabled = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    compact = true
    show_app_actions = true

    [shell.panel]
    launcher_placement = "attached"

    [shell.screen_corners]
    enabled = true
    size = 26

[theme]
source = "wallpaper"
wallpaper_scheme = "vibrant"

[wallpaper]
directory = "/home/licryle/Pictures"

    [wallpaper.default]
    path = "/home/licryle/Pictures/wallpaper.png"

    [wallpaper.last]
    path = "/home/licryle/Pictures/wallpaper.png"

[widget.brightness]
enabled = false

[widget.media]
hide_when_no_media = true

[widget.wallpaper]
enabled = false
